/**
 * @description Exception messages and codes
 */
export default {
  UNAUTHORIZED: {
    TOKEN_REQUIRED: "Token required",
    TOKEN_UNAUTHORIZED: "Invalid token"
  },
  BAD_REQUEST: {
    INVALID_BODY: "INVALID_BODY",

    USER: {
      NAME_MUST_BE_STRING: "NAME_MUST_BE_STRING",
      NAME_REQUIRED: "NAME_REQUIRED",
      AVATAR_MUST_BE_STRING: "AVATAR_MUST_BE_STRING",
      AVATAR_REQUIRED: "AVATAR_REQUIRED"
    },
    ARTICLE: {
      USER_ID_MUST_BE_STRING: "USER_ID_MUST_BE_STRING",
      USER_ID_REQUIRED: "USER_ID_REQUIRED",
      TITLE_MUST_BE_STRING: "TITLE_MUST_BE_STRING",
      TITLE_REQUIRED: "TITLE_REQUIRED",
      TEXT_MUST_BE_STRING: "TEXT_MUST_BE_STRING",
      TEXT_REQUIRED: "TEXT_REQUIRED",
      TAGS_MUST_BE_ARRAY: "TAGS_MUST_BE_ARRAY",
      TAGS_REQUIRED: "TAGS_REQUIRED",
      USER_NOT_EXISTS: "USER_NOT_EXISTS",
      TAG_MUST_BE_STRING: "TAG_MUST_BE_STRING",
      USER_ID_INVALID_FORMAT: "USER_ID_INVALID_FORMAT"
    }
  }
};